title: USAR Legal Directory
baseurl: "/legal-directory"
url: "https://usarscotus.github.io"
description: A directory of legal resources for the USAR Community on ROBLOX.
markdown: kramdown
collections:
  frap:
    output: true
  frcp:
    output: true
  frcmp:
    output: true
  fre:
    output: true
  supct:
    output: true
# CourtListener API token used by the case search page
COURTLISTENER_TOKEN: "8671b4a853776a65c3d1393858c138e4951a246e"
