title: USAR Legal Directory
baseurl: "/legal-directory"
url: "https://usarscotus.github.io"
description: A directory of legal resources for the USAR Community on ROBLOX.
markdown: kramdown
collections:
  frap:
    output: true
  frcp:
    output: true
  frcmp:
    output: true
  fre:
    output: true
  supct:
    output: true
# CourtListener API token: set via COURTLISTENER_TOKEN environment variable when building
COURTLISTENER_TOKEN: ""
